[workspace]
resolver = "2"
members = [
    ".isar/packages/isar_core",
    ".isar/packages/isar_core_ffi",
    ".isar/packages/mdbx_sys"
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"