name: anynotedotai
description: This is a simple note app built using Flutter and GetX
version: 1.0.19+19
environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: 3.24.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  url_launcher: ^6.3.0
  flutter_launcher_icons: '>=0.13.1 <0.15.0'
  hidden_drawer_menu: ^3.0.1
  path_provider: ^2.1.5
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^4.0.0
  pub_semver: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: '>=4.0.0 <6.0.0'
  build_runner: ^2.4.13
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
flutter:
  uses-material-design: true
flutter_launcher_icons:
  android: true
  image_path: assets/logo.png
