default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Internal track"
  lane :internal do 
    upload_to_play_store(
      track: 'internal',
      aab: './release/AnyNote.AI.aab',
      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_aab: false,
    )
  end
end
