name: Flutter Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Build Android bundle
        uses: AcmeSoftwareLLC/flutter-build@v1
        with:
          platform: android
          build-name: 1.0.0
          build-number: 20231005
          pub-get: true
          gen-icons: false
