name: Build and Release Flutter App
on:
    push:
        branches:
            - main
    workflow_dispatch:
permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.pub-cache
                  key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
                  restore-keys: ${{ runner.os }}-pub-
            - name: Install dependencies
              uses: upciti/wakemeops-action@v1
              with:
                  packages: dasel
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"
            # - name: Setup Android SDK Tools
            #   uses: android-actions/setup-android@v3.2.1
            - name: Generate keystore.properties
              run: |
                  cat <<EOF > ./android/key.properties
                  storePassword=${{ secrets.KEYSTORE_PASSWORD }}
                  keyPassword=${{ secrets.KEYSTORE_PASSWORD }}
                  keyAlias=upload
                  storeFile=./upload-keystore.jks
                  EOF
            - name: Decode keystore and create jks
              run: echo "${{ secrets.KEYSTORE_JKS_BASE64 }}" | base64 --decode > ./android/app/upload-keystore.jks
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"
                  cache: true
            - name: Clean
              run: flutter clean
            - name: Install dependencies
              run: flutter pub get
            - name: Build APK
              run: flutter build apk --release
            - name: Build AppBundle
              run: flutter build appbundle
            - name: Rename APK
              run: mv ./build/app/outputs/flutter-apk/app-release.apk ./AnyNote.AI.apk
            - name: Rename AppBundle
              run: mv ./build/app/outputs/bundle/release/app-release.aab ./AnyNote.AI.aab
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: Releases
                  path: |
                      ./AnyNote.AI.apk
                      ./AnyNote.AI.aab
            - name: Extract version from pubspec.yaml
              id: extract_version
              run: |
                  version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
                  echo "VERSION=$version" >> $GITHUB_ENV
            - name: Check if Tag Exists
              id: check_tag
              run: |
                  if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
                    echo "TAG_EXISTS=true" >> $GITHUB_ENV
                  else
                    echo "TAG_EXISTS=false" >> $GITHUB_ENV
                  fi
            - name: Modify Tag
              if: env.TAG_EXISTS == 'true'
              id: modify_tag
              run: |
                  new_version=${{ env.VERSION }}+0.0.1
                  echo "VERSION=$new_version" >> $GITHUB_ENV
            - name: Update YAML file
              run: |
                  dasel put -t string -f pubspec.yaml -r yaml -v ${{ env.VERSION }} "version"
            - name: Commit and Push
              run: |
                  git config --global user.email "mohamed.hisham.abdelzaher@gmail.com"
                  git config --global user.name "Mohamed Hisham Abdelzaher"
                  git add pubspec.yaml
                  git commit -m "Update version to ${{ env.VERSION }}"
                  git push
            - name: Create Release
              run: |
                  gh release create ${{ env.VERSION }} \
                      --repo=MH0386/anynotedotai \
                      --title="Version v${{ env.VERSION }}" \
                      --generate-notes \
                      --latest
            - name: Upload Assets
              run: |
                  gh release upload ${{ env.VERSION }} \
                  ./AnyNote.AI.apk \
                  ./AnyNote.AI.aab \
                  --clobber

    # release:
    #     needs: build
    #     runs-on: ubuntu-latest
    #     env:
    #         GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    #     steps:
    #         - name: Download APK
    #           uses: actions/download-artifact@v4
    #           with:
    #               name: Releases
    #               path: .
    #         - name: Create GitHub Release
    #           id: create_release
    #           uses: actions/create-release@v1
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    #           with:
    #               tag_name: ${{ github.ref_name }}
    #               release_name: Release ${{ github.ref_name }}
    #               draft: false
    #               prerelease: false
    #         - name: Upload APK to Release
    #           uses: actions/upload-release-asset@v1
    #           env:
    #               GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    #           with:
    #               upload_url: ${{ steps.create_release.outputs.upload_url }}
    #               asset_path: ./app-release.apk
    #               asset_name: app-release.apk
    #               asset_content_type: application/vnd.android.package-archive
